version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"  # Le port 3306 est mappé du conteneur vers l'hôte
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
